[refactor] bump packages version (angular, firebase, etc)
patrickgdl/akademic pull request #1
Opened 2022-01-28 01:37 UTC by patrickgdl

Let's revive this project? I have a lot of new ideas and a new layout is almost done. Check it [here](https://www.figma.com/file/qTJGVQprFSYcbCZHe5BRCL/Dashboard-Akademic?node-id=0%3A1).

The first thing for it is updating this project, the following things were updated:

- [x] @angular/* - from v6 to v12
- [x] angularfire2 to @angular/fire v6
- [x] primeng from v6 to v12 (I hope we someway drop this package, it's huge and we have a lot of possibilities, let's talk about it
- [x] bootstrap from v3 to v5 (this one is requires attention, because it broke **everything**, but it's ok because can we study now different approachs, like [Tailwind](https://tailwindcss.com/), maybe? Or pure SASS/CSS. Or even @angular/material or any other lib ui. Bootstrap today is so boring...

Updating Angular and Firebase there is a lot of breaking changes, you can see for yourself on the last 10 commits.

Hope you get excited as I am and let's f*cking do it!

2022-02-24 20:35 UTC, luizhc commented
Reviewed pull request. ✅

Just a simple line of code need to be adjust, otherwise it's perfect @patrickgdl 🎉🚀

2022-02-25 16:55 UTC, luizhc requested changes

2022-02-25 16:55 UTC, luizhc commented on src/app/app.routing.ts
> +    loadChildren: './features/student/student.module#StudentModule',
new lazy loading missing

2022-02-26 01:54 UTC, patrickgdl commented on src/app/app.routing.ts
> +    loadChildren: './features/student/student.module#StudentModule',
Fixed.

2022-03-01 19:52 UTC, luizhc approved these changes
Perfect, thank you! 🚀

2022-03-01 19:53 UTC, merged